spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: testuser
    password: testpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: samsohn0128@gmail.com
    password: xlvaaquckeeofzqs
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true